ci/terraform: Upgrade pip to latest
The installation of `python-openstackclient` was failing due to some
error when setting up the `cryptography` dependency:

```
Collecting cryptography>=2.7 (from openstacksdk>=0.48.0->python-openstackclient)
  Using cached https://files.pythonhosted.org/packages/f8/04/51dc8a4ccb37b69a4e165a94837f70653b0b6ca49a6346361062b1f6bb09/cryptography-3.4.3.tar.gz
    Complete output from command python setup.py egg_info:
        =============================DEBUG ASSISTANCE==========================
        If you are seeing an error here please try the following to
        successfully install cryptography:
        Upgrade to the latest pip and try again. This will fix errors for most
        users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jhyfo9j0/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

Upgrading `pip` to the latest version fixes this issue.

(cherry picked from commit b216945e7616d2056c88870bfebfe007109fce82)