pre-commit/buildchain: Bump mypy version to v0.910
Also add some dependencies for Yaml and Jinja2 typing, and fix some
error because of invalid `type: ignore`

```
buildchain/buildchain/targets/serialize.py:164: error: unused "type: ignore" comment
buildchain/buildchain/targets/serialize.py:165: error: Argument 2 to "add_representer" of "BaseRepresenter" has incompatible type "Callable[[BaseDumper, Any], Any]"; expected "Callable[[SafeDumper, ByteString], Node]"
buildchain/buildchain/targets/serialize.py:170: error: unused "type: ignore" comment
```